# Site settings
title: John Quach
description: Welcome to my perfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: John Quach
user_description: After 20 years working as an Oracle Specialist I decided to take the bold move and re-skill as a Web Developer. I'm really excited about trying new frameworks and libraries to further improve myself and bring ideas to reality.
user_title: Web Developer
email: john.dv.quach@gamil.com
twitter_username: jbond034
github_username:  jdquach.com
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
